export const categoriesList = '.list-group #itemc'
export const itemsOnHomepage = '#tbodyid .card'
export const navMenuButton = 'a.nav-link'
export const aboutUsVideoModal = '#videoModal'
export const loggedInUsername = '#nameofuser'